from pathlib import Path

# Phase 0 setup defaults
EXPECTED_PYTHON_MAJOR = 3
EXPECTED_PYTHON_MINOR = 11

PROJECT_ROOT = Path(__file__).resolve().parent
ASSETS_DIR = PROJECT_ROOT / "assets"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
ROM_PATH = ASSETS_DIR / "pokemon_red.gb"
BATTLE_STATE_PATH = ASSETS_DIR / "states" / "battle_rattata.state"
DEFAULT_NAV_STATE_PATH = ASSETS_DIR / "states" / "explore_start.state"
ENV_FILE_PATH = PROJECT_ROOT / ".env.local"
DEFAULT_CAMPAIGN_LOG_PATH = ARTIFACTS_DIR / "campaign_log.json"
DEFAULT_PHASE3_OUTPUT_PATH = ARTIFACTS_DIR / "results" / "exploration_results.json"
DEFAULT_PHASE3_SUMMARY_PATH = ARTIFACTS_DIR / "results" / "RESULTS.md"
DEFAULT_PHASE4_START_STATE_PATH = ASSETS_DIR / "states" / "explore_start.state"
DEFAULT_PHASE4_ROUTE_SCRIPT_PATH = ASSETS_DIR / "routes" / "route1_to_pewter.json"
DEFAULT_PHASE4_RESULTS_PATH = ARTIFACTS_DIR / "results" / "phase4_results.json"
DEFAULT_PHASE4_TIMELINE_PATH = ARTIFACTS_DIR / "results" / "phase4_timeline.jsonl"
DEFAULT_PHASE4_TIMELAPSE_PATH = ARTIFACTS_DIR / "results" / "phase4_timelapse.txt"
DEFAULT_PHASE4_LAST_GOOD_RESULTS_PATH = ARTIFACTS_DIR / "results" / "phase4_last_good_results.json"
DEFAULT_PHASE4_LAST_GOOD_TIMELINE_PATH = ARTIFACTS_DIR / "results" / "phase4_last_good_timeline.jsonl"
DEFAULT_PHASE4_WILD_BATTLE_MODE = "run_first"
DEFAULT_PHASE4_FARM_HP_THRESHOLD = 0.45
DEFAULT_PHASE4_FARM_MAX_CONSECUTIVE_FIGHTS = 3
DEFAULT_PHASE5_START_STATE_PATH = ASSETS_DIR / "states" / "before_brock.state"
DEFAULT_PHASE5_ROUTE_SCRIPT_PATH = ASSETS_DIR / "routes" / "pewter_gym_to_brock_badge.json"
DEFAULT_PHASE5_RESULTS_PATH = ARTIFACTS_DIR / "results" / "phase5_results.json"
DEFAULT_PHASE5_TIMELINE_PATH = ARTIFACTS_DIR / "results" / "phase5_timeline.jsonl"
DEFAULT_PHASE5_REQUIRED_SPECIES = 176
DEFAULT_PHASE5_STRENGTH_MIN_LEVEL = 16
DEFAULT_PHASE5_STRENGTH_RUNS = 10
DEFAULT_PHASE5_STRENGTH_PASS_RATE = 0.70
DEFAULT_PHASE5_STRENGTH_CHECK = "strict"
DEFAULT_BATTLE_SCREENSHOTS_ENABLED = True
DEFAULT_BATTLE_SCREENSHOTS_DIR = ARTIFACTS_DIR / "screenshots" / "battles"
DEFAULT_BATTLE_SCREENSHOT_RETAIN_BATTLES = 25

RAM_ADDR_X_POS = 0xD362
RAM_ADDR_Y_POS = 0xD361
RAM_ADDR_MAP_ID = 0xD35E
RAM_ADDR_BADGES = 0xD356
RAM_ADDR_PLAYER_HP = 0xD16C

MIN_NONEMPTY_FILE_BYTES = 1

# Phase 1 battle RAM map
RAM_ADDR_IN_BATTLE = 0xD057
RAM_ADDR_PLAYER_MAX_HP = 0xD18D
RAM_ADDR_PLAYER_LEVEL = 0xD18C
RAM_ADDR_PLAYER_SPECIES = 0xD16B
RAM_ADDR_ENEMY_HP = 0xCFE6
RAM_ADDR_ENEMY_LEVEL = 0xCFE8
RAM_ADDR_ENEMY_SPECIES = 0xCFE5
RAM_ADDR_PLAYER_MOVE_1 = 0xD01C
RAM_ADDR_PLAYER_MOVE_2 = 0xD01D
RAM_ADDR_PLAYER_MOVE_3 = 0xD01E
RAM_ADDR_PLAYER_MOVE_4 = 0xD01F
RAM_ADDR_PLAYER_MOVE_PP_1 = 0xD02C
RAM_ADDR_PLAYER_MOVE_PP_2 = 0xD02D
RAM_ADDR_PLAYER_MOVE_PP_3 = 0xD02E
RAM_ADDR_PLAYER_MOVE_PP_4 = 0xD02F
RAM_ADDR_PARTY_COUNT = 0xD163
RAM_ADDR_PARTY_SPECIES_START = 0xD164
RAM_ADDR_PARTY_MON_START = 0xD16B
PARTY_MON_STRUCT_SIZE = 0x2C
PARTY_MON_LEVEL_OFFSET = 0x21
MAX_PARTY_SIZE = 6

# Phase 1 runtime defaults
DEFAULT_MODEL = "mistral-large-latest"
DEFAULT_EPISODES = 30
DEFAULT_UPDATE_EVERY = 5
DEFAULT_MAX_TURNS = 60
DEFAULT_BATTLE_WAIT_TICKS = 12000
DEFAULT_TURN_TICK_BUDGET = 1200
DEFAULT_BUTTON_HOLD_FRAMES = 8
DEFAULT_POST_INPUT_TICKS = 24
DEFAULT_BATTLE_SEARCH_STEPS = 220
DEFAULT_LLM_TURN_INTERVAL = 3
DEFAULT_MAX_DECISION_CALLS = 120
DEFAULT_MAX_REFLECTION_CALLS = 5
DEFAULT_MEMORY_PATH = ARTIFACTS_DIR / "memory" / "battle_memory.json"
DEFAULT_MEMORY_SNAPSHOT_KEEP = 10
DEFAULT_PHASE2B_TARGET_STATE_INDEX = 3
DEFAULT_PHASE2B_MIN_TURN_IMPROVEMENT = 1.0
