from pathlib import Path

# Phase 0 setup defaults
EXPECTED_PYTHON_MAJOR = 3
EXPECTED_PYTHON_MINOR = 11

PROJECT_ROOT = Path(__file__).resolve().parent
ASSETS_DIR = PROJECT_ROOT / "assets"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
ROM_PATH = ASSETS_DIR / "pokemon_red.gb"
BATTLE_STATE_PATH = ASSETS_DIR / "states" / "battle_rattata.state"
ENV_FILE_PATH = PROJECT_ROOT / ".env.local"
DEFAULT_CAMPAIGN_LOG_PATH = ARTIFACTS_DIR / "campaign_log.json"

RAM_ADDR_X_POS = 0xD362
RAM_ADDR_PLAYER_HP = 0xD16C

MIN_NONEMPTY_FILE_BYTES = 1

# Phase 1 battle RAM map
RAM_ADDR_IN_BATTLE = 0xD057
RAM_ADDR_PLAYER_MAX_HP = 0xD18D
RAM_ADDR_PLAYER_LEVEL = 0xD18C
RAM_ADDR_PLAYER_SPECIES = 0xD16B
RAM_ADDR_ENEMY_HP = 0xCFE6
RAM_ADDR_ENEMY_LEVEL = 0xCFE8
RAM_ADDR_ENEMY_SPECIES = 0xCFE5
RAM_ADDR_PLAYER_MOVE_1 = 0xD01C
RAM_ADDR_PLAYER_MOVE_2 = 0xD01D
RAM_ADDR_PLAYER_MOVE_3 = 0xD01E
RAM_ADDR_PLAYER_MOVE_4 = 0xD01F
RAM_ADDR_PLAYER_MOVE_PP_1 = 0xD02C
RAM_ADDR_PLAYER_MOVE_PP_2 = 0xD02D
RAM_ADDR_PLAYER_MOVE_PP_3 = 0xD02E
RAM_ADDR_PLAYER_MOVE_PP_4 = 0xD02F

# Phase 1 runtime defaults
DEFAULT_MODEL = "mistral-large-latest"
DEFAULT_EPISODES = 30
DEFAULT_UPDATE_EVERY = 5
DEFAULT_MAX_TURNS = 60
DEFAULT_BATTLE_WAIT_TICKS = 12000
DEFAULT_TURN_TICK_BUDGET = 1200
DEFAULT_BUTTON_HOLD_FRAMES = 8
DEFAULT_POST_INPUT_TICKS = 24
DEFAULT_BATTLE_SEARCH_STEPS = 220
DEFAULT_LLM_TURN_INTERVAL = 3
DEFAULT_MAX_DECISION_CALLS = 120
DEFAULT_MAX_REFLECTION_CALLS = 5
